import { Product } from "./types";

export const CATEGORIES = ["All", "Electronics", "Clothing", "Home & Living", "Sports", "Beauty"];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    price: 79.99,
    originalPrice: 129.99,
    image: "https://m.media-amazon.com/images/I/71YM2N5whtL.jpg",
    category: "Electronics",
    rating: 4.8,
    reviewCount: 2341,
    badge: "bestseller",
    description: "Premium sound quality with 30-hour battery life and active noise cancellation.",
    inStock: true,
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    price: 149.00,
    originalPrice: 199.00,
    image: "https://fossil.scene7.com/is/image/FossilPartners/FS5304_9L?$sfcc_lifestyle_medium_watches$",
    category: "Clothing",
    rating: 4.6,
    reviewCount: 876,
    badge: "sale",
    description: "Elegant timepiece with genuine leather strap and sapphire crystal glass.",
    inStock: true,
  },
  {
    id: 3,
    name: "Smart Fitness Tracker Band",
    price: 49.99,
    image: "https://m.media-amazon.com/images/I/71KwGt+7qSL._AC_UF894,1000_QL80_DpWeblab_.jpg",
    category: "Sports",
    rating: 4.5,
    reviewCount: 1203,
    badge: "new",
    description: "Track your steps, heart rate, sleep, and calories with 7-day battery life.",
    inStock: true,
  },
  {
    id: 4,
    name: "Ceramic Pour-Over Coffee Set",
    price: 64.00,
    originalPrice: 80.00,
    image: "https://m.media-amazon.com/images/I/7159+ELcEOL._AC_UF894,1000_QL80_.jpg",
    category: "Home & Living",
    rating: 4.9,
    reviewCount: 542,
    badge: "featured",
    description: "Handcrafted ceramic dripper with matching carafe for the perfect morning brew.",
    inStock: true,
  },
  {
    id: 5,
    name: "Ultra-Slim Laptop Stand",
    price: 39.99,
    image: "https://m.media-amazon.com/images/I/61zXuhUdjwL.jpg",
    category: "Electronics",
    rating: 4.4,
    reviewCount: 987,
    description: "Adjustable aluminum stand compatible with all laptops up to 17 inches.",
    inStock: true,
  },
  {
    id: 6,
    name: "Organic Vitamin C Serum",
    price: 34.99,
    originalPrice: 49.99,
    image: "https://m.media-amazon.com/images/I/615YQQ63jfL._AC_UF1000,1000_QL80_.jpg",
    category: "Beauty",
    rating: 4.7,
    reviewCount: 3102,
    badge: "bestseller",
    description: "Brightening serum with 20% Vitamin C, hyaluronic acid, and vitamin E.",
    inStock: true,
  },
  {
    id: 7,
    name: "Merino Wool Crewneck Sweater",
    price: 89.00,
    image: "https://images.hawesandcurtis.com/tr:q-80/JW/JWPWH004-G01-206489-1400px-1820px.jpg",
    category: "Clothing",
    rating: 4.6,
    reviewCount: 431,
    badge: "new",
    description: "Sustainably sourced 100% merino wool in a classic relaxed fit.",
    inStock: true,
  },
  {
    id: 8,
    name: "Yoga Mat with Alignment Lines",
    price: 55.00,
    originalPrice: 75.00,
    image: "https://cdn.shopify.com/s/files/1/0868/4453/9204/files/TPE_Alignment_Mat_Image_02v2_480x480.jpg?v=1737458389",
    category: "Sports",
    rating: 4.8,
    reviewCount: 1567,
    badge: "sale",
    description: "Non-slip 6mm thick eco-friendly mat with printed alignment guides.",
    inStock: true,
  },
  {
    id: 9,
    name: "Scented Soy Candle Set",
    price: 42.00,
    image: "http://www.melodysusie.com/cdn/shop/products/scented-candle-set-4_f569cf14-c186-4f40-8c7a-2846415bcb7c_1.jpg?v=1672395020&width=2048",
    category: "Home & Living",
    rating: 4.5,
    reviewCount: 728,
    description: "Set of 3 hand-poured soy candles in lavender, cedar, and vanilla scents.",
    inStock: true,
  },
  {
    id: 10,
    name: "Portable Bluetooth Speaker",
    price: 59.99,
    originalPrice: 89.99,
    image: "https://cdn.thewirecutter.com/wp-content/media/2024/11/portablebluetoothspeakers-2048px-9130.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    category: "Electronics",
    rating: 4.7,
    reviewCount: 2089,
    badge: "sale",
    description: "360° surround sound with waterproof design and 12-hour playtime.",
    inStock: true,
  },
  {
    id: 11,
    name: "Retinol Night Cream",
    price: 44.99,
    image: "https://pics.walgreens.com/prodimg/629250/900.jpg",
    category: "Beauty",
    rating: 4.6,
    reviewCount: 1834,
    description: "Advanced anti-aging formula with 0.5% retinol and peptide complex.",
    inStock: false,
  },
  {
    id: 12,
    name: "Linen Throw Blanket",
    price: 68.00,
    originalPrice: 90.00,
    image: "https://m.media-amazon.com/images/I/71EUmwZhM6L.jpg",
    category: "Home & Living",
    rating: 4.8,
    reviewCount: 612,
    badge: "featured",
    description: "Stonewashed linen throw in a generous 130×170cm size, perfect for any sofa.",
    inStock: true,
  },
];
